/// Builds an sRGB ICC v2 profile.
///
/// PDF/A requires an output intent naming an ICC profile, and that profile has
/// to be IN the file. Rather than shipping someone else's binary - with its
/// licence to check and its bytes to trust - Folio constructs one. Every value
/// here comes from the sRGB specification (IEC 61966-2-1) and the ICC v2
/// specification, and the tests decode the result back rather than comparing
/// it against the code that wrote it.
///
/// A matrix/TRC display profile: three colourant tags, three tone curves, a
/// white point, a description and a copyright. That is the whole of what a
/// well-formed RGB profile needs.
library;

import 'dart:math' as math;
import 'dart:typed_data';

/// Entries in each tone curve. 1024 is what the reference sRGB profiles use;
/// it is fine enough that the sampling error is below one part in 65535.
const _curvePoints = 1024;

/// sRGB primaries, chromatically adapted to the D50 white point the ICC
/// profile connection space is defined at. These are the adapted values, not
/// the D65 ones: a profile carrying unadapted primaries is subtly wrong in a
/// way nothing warns about.
const _red = [0.4360, 0.2225, 0.0139];
const _green = [0.3851, 0.7169, 0.0971];
const _blue = [0.1431, 0.0606, 0.7139];

/// D50, the PCS illuminant.
const _whitePoint = [0.9642, 1.0000, 0.8249];

Uint8List buildSrgbIccProfile() {
  final tags = <String, List<int>>{
    'desc': _textDescription('sRGB IEC61966-2.1'),
    'cprt': _text('No copyright, generated by Folio'),
    'wtpt': _xyz(_whitePoint),
    'rXYZ': _xyz(_red),
    'gXYZ': _xyz(_green),
    'bXYZ': _xyz(_blue),
  };

  // One curve, referenced by all three channels. Identical tags may share
  // their data, and three copies of two kilobytes would be three copies.
  final curve = _curve();

  final names = [...tags.keys, 'rTRC', 'gTRC', 'bTRC'];
  final headerSize = 128 + 4 + names.length * 12;

  final data = <int>[];
  final placement = <String, ({int offset, int size})>{};

  for (final entry in tags.entries) {
    while (data.length % 4 != 0) {
      data.add(0);
    }
    placement[entry.key] = (
      offset: headerSize + data.length,
      size: entry.value.length,
    );
    data.addAll(entry.value);
  }

  while (data.length % 4 != 0) {
    data.add(0);
  }
  final curvePlace = (offset: headerSize + data.length, size: curve.length);
  data.addAll(curve);
  for (final channel in ['rTRC', 'gTRC', 'bTRC']) {
    placement[channel] = curvePlace;
  }

  final size = headerSize + data.length;
  final out = <int>[..._header(size), ..._uint32(names.length)];
  for (final name in names) {
    out
      ..addAll(_signature(name))
      ..addAll(_uint32(placement[name]!.offset))
      ..addAll(_uint32(placement[name]!.size));
  }
  out.addAll(data);

  return Uint8List.fromList(out);
}

List<int> _header(int size) {
  final out = <int>[..._uint32(size)];
  out
    ..addAll(_uint32(0)) // preferred CMM: none in particular
    ..addAll(_uint32(0x02100000)) // version 2.1
    ..addAll(_signature('mntr'))
    ..addAll(_signature('RGB '))
    ..addAll(_signature('XYZ '));

  // Creation date, fixed rather than "now": a profile that changes every time
  // it is built makes two conversions of the same document differ.
  for (final part in [2026, 1, 1, 0, 0, 0]) {
    out.addAll(_uint16(part));
  }

  out
    ..addAll(_signature('acsp'))
    ..addAll(_uint32(0)) // platform
    ..addAll(_uint32(0)) // flags: not embedded elsewhere, use anywhere
    ..addAll(_uint32(0)) // device manufacturer
    ..addAll(_uint32(0)) // device model
    ..addAll(_uint32(0)) // device attributes, high
    ..addAll(_uint32(0)) // device attributes, low
    ..addAll(_uint32(0)); // rendering intent: perceptual

  for (final value in _whitePoint) {
    out.addAll(_s15Fixed16(value));
  }

  out
    ..addAll(_uint32(0)) // profile creator
    ..addAll(List.filled(16, 0)) // profile id: unset
    ..addAll(List.filled(28, 0)); // reserved

  return out;
}

/// The sRGB tone reproduction curve, as device value to linear light.
///
/// The piecewise definition matters at the dark end: a plain 2.2 gamma is
/// visibly wrong in shadows, which on a scanned page is most of the ink.
List<int> _curve() {
  final out = <int>[
    ..._signature('curv'),
    ..._uint32(0),
    ..._uint32(_curvePoints),
  ];

  for (var i = 0; i < _curvePoints; i++) {
    final u = i / (_curvePoints - 1);
    final linear = u <= 0.04045
        ? u / 12.92
        : math.pow((u + 0.055) / 1.055, 2.4).toDouble();
    out.addAll(_uint16((linear * 65535).round().clamp(0, 65535)));
  }

  return out;
}

List<int> _xyz(List<double> values) => [
  ..._signature('XYZ '),
  ..._uint32(0),
  for (final value in values) ..._s15Fixed16(value),
];

List<int> _text(String value) => [
  ..._signature('text'),
  ..._uint32(0),
  ...value.codeUnits,
  0,
];

/// ICC v2's `textDescriptionType`, which carries the same words three times:
/// ASCII, UTF-16 and Macintosh script code. The last two are left empty, which
/// is legal, but their length fields and the 67-byte script buffer are not
/// optional - a profile missing them fails validation.
List<int> _textDescription(String value) => [
  ..._signature('desc'),
  ..._uint32(0),
  ..._uint32(value.length + 1),
  ...value.codeUnits,
  0,
  ..._uint32(0), // Unicode language code
  ..._uint32(0), // Unicode count
  0, 0, // Macintosh script code
  0, // Macintosh description length
  ...List.filled(67, 0),
];

List<int> _signature(String value) => value.codeUnits;

List<int> _uint32(int value) => [
  (value >> 24) & 0xFF,
  (value >> 16) & 0xFF,
  (value >> 8) & 0xFF,
  value & 0xFF,
];

List<int> _uint16(int value) => [(value >> 8) & 0xFF, value & 0xFF];

List<int> _s15Fixed16(double value) => _uint32((value * 65536).round());
